In [7]:
import pandas as pd

inv_total_tradingday_df = pd.read_csv('/home/dalong/bruce/Task8_Reproduce_Report/data/inventory_total_TradingDays.csv', index_col=0)

In [8]:
inv_total_tradingday_df

,al,cu,ni,pb,sn,zn,bu,l,MA,pp,...,FG,hc,i,j,jm,rb,ZC,ag,au,ru
2010/1/4,4624425,634252,158424,146775,26795,651436,NaN,34135,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,99263,7600000,3496.77,305.92,108320
2010/1/5,4624125,637733,158424,147175,26795,651411,NaN,34135,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,117293,7751900,3498.81,305.88,108320
2010/1/6,4619850,640757,158388,147850,26795,651911,NaN,34435,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,122743,7670600,3498.75,306.07,109100
2010/1/7,4615400,640683,158814,149150,26860,652737,NaN,34435,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,125441,7509000,3475.26,306.06,109200
2010/1/8,4613400,643732,158982,149375,26910,654965,NaN,18585,NaN,NaN,...,NaN,4282910.0,66170000.0,NaN,NaN,139167,7258000,3482.64,309.12,256233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017/12/25,1808745,446231,405878,178095,6731,197692,177450.0,21230,332800.0,13480.0,...,1583040.0,1768761.0,145365700.0,2726000.0,1871000.0,3100400,30016100,8777.69,286.74,661298
2017/12/26,1809196,448408,405878,178070,6803,197392,173150.0,19495,332800.0,13180.0,...,1569040.0,1768761.0,145365700.0,2726000.0,1871000.0,3100400,29866900,8796.98,286.74,663078
2017/12/27,1809095,449308,404000,177470,6764,195418,173150.0,19495,332800.0,13080.0,...,1569040.0,1768761.0,145365700.0,2726000.0,1871000.0,3100400,29917900,8798.43,286.65,665108
2017/12/28,1809891,450586,402788,176939,6690,193643,170150.0,19495,332800.0,12680.0,...,1569040.0,1768761.0,145365700.0,2726000.0,1871000.0,3100400,29664600,8824.89,286.65,666948
2017/12/29,1811353,455201,399728,176790,6680,191439,182980.0,19195,341600.0,12060.0,...,1563540.0,1708400.0,146550900.0,2831000.0,2070000.0,3183700,29344900,8910.32,286.65,688639

In [31]:
rolling = 2

signal_df = inv_total_tradingday_df.diff(rolling - 1) / inv_total_tradingday_df.shift(rolling - 1)

In [37]:
signal_df

,al,cu,ni,pb,sn,zn,bu,l,MA,pp,...,FG,hc,i,j,jm,rb,ZC,ag,au,ru
2010/1/4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010/1/5,-0.000065,0.005488,0.000000,0.002725,0.000000,-0.000038,NaN,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.181639,0.019987,0.000583,-0.000131,0.000000
2010/1/6,-0.000538,0.005078,-0.000125,0.003749,0.000000,0.000405,NaN,0.004834,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.107293,0.003226,0.000253,0.000283,0.003960
2010/1/7,-0.000709,0.002990,0.001006,0.005776,0.000975,0.000751,NaN,0.002891,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.072998,-0.006540,-0.002548,0.000156,0.002737
2010/1/8,-0.000618,0.003573,0.001023,0.004370,0.001267,0.001628,NaN,-0.149706,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.084998,-0.015398,-0.001009,0.003399,0.445432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017/12/25,0.000956,0.002166,-0.000307,0.001694,-0.010753,-0.008262,-0.000405,-0.006094,0.000335,-0.031893,...,0.001203,-0.004225,0.002749,0.000456,-0.015748,0.003897,-0.004518,0.000310,0.000172,0.008987
2017/12/26,0.000828,0.002659,-0.000251,0.001361,-0.006853,-0.007036,-0.004737,-0.019845,0.000274,-0.030140,...,-0.000624,-0.003457,0.002249,0.000373,-0.012885,0.003188,-0.004600,0.000653,0.000140,0.007843
2017/12/27,0.000667,0.002541,-0.001047,0.000501,-0.006649,-0.007575,-0.003876,-0.016237,0.000224,-0.026040,...,-0.000511,-0.002828,0.001840,0.000305,-0.010542,0.002609,-0.003453,0.000565,0.000058,0.006973
2017/12/28,0.000626,0.002596,-0.001402,-0.000134,-0.007430,-0.007849,-0.006321,-0.013285,0.000184,-0.026865,...,-0.000418,-0.002314,0.001506,0.000250,-0.008626,0.002134,-0.004365,0.001009,0.000047,0.006208
2017/12/29,0.000659,0.003986,-0.002528,-0.000263,-0.006351,-0.008492,0.008538,-0.013667,0.004958,-0.030871,...,-0.000979,-0.008098,0.002714,0.007208,0.012281,0.006631,-0.005531,0.002585,0.000039,0.010993

In [35]:
import pandas as pd

signal_df = pd.DataFrame.ewm(signal_df, span=10).mean()

In [34]:
pd.DataFrame.ewm(signal_df, span=10).mean()

,al,cu,ni,pb,sn,zn,bu,l,MA,pp,...,FG,hc,i,j,jm,rb,ZC,ag,au,ru
2010/1/4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010/1/5,-0.000065,0.005488,0.000000,0.002725,0.000000,-0.000038,NaN,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.181639,0.019987,0.000583,-0.000131,0.000000
2010/1/6,-0.000538,0.005078,-0.000125,0.003749,0.000000,0.000405,NaN,0.004834,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.107293,0.003226,0.000253,0.000283,0.003960
2010/1/7,-0.000709,0.002990,0.001006,0.005776,0.000975,0.000751,NaN,0.002891,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.072998,-0.006540,-0.002548,0.000156,0.002737
2010/1/8,-0.000618,0.003573,0.001023,0.004370,0.001267,0.001628,NaN,-0.149706,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.084998,-0.015398,-0.001009,0.003399,0.445432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017/12/25,0.000956,0.002166,-0.000307,0.001694,-0.010753,-0.008262,-0.000405,-0.006094,0.000335,-0.031893,...,0.001203,-0.004225,0.002749,0.000456,-0.015748,0.003897,-0.004518,0.000310,0.000172,0.008987
2017/12/26,0.000828,0.002659,-0.000251,0.001361,-0.006853,-0.007036,-0.004737,-0.019845,0.000274,-0.030140,...,-0.000624,-0.003457,0.002249,0.000373,-0.012885,0.003188,-0.004600,0.000653,0.000140,0.007843
2017/12/27,0.000667,0.002541,-0.001047,0.000501,-0.006649,-0.007575,-0.003876,-0.016237,0.000224,-0.026040,...,-0.000511,-0.002828,0.001840,0.000305,-0.010542,0.002609,-0.003453,0.000565,0.000058,0.006973
2017/12/28,0.000626,0.002596,-0.001402,-0.000134,-0.007430,-0.007849,-0.006321,-0.013285,0.000184,-0.026865,...,-0.000418,-0.002314,0.001506,0.000250,-0.008626,0.002134,-0.004365,0.001009,0.000047,0.006208
2017/12/29,0.000659,0.003986,-0.002528,-0.000263,-0.006351,-0.008492,0.008538,-0.013667,0.004958,-0.030871,...,-0.000979,-0.008098,0.002714,0.007208,0.012281,0.006631,-0.005531,0.002585,0.000039,0.010993

In [45]:
import numpy as np

pd.Series([np.nan, 2, 3, -2, -6]).dropna().sort_values(ascending=False)

2    3.0
1    2.0
3   -2.0
4   -6.0
dtype: float64

In [43]:
pd.Series([np.nan, 2, 3, -2, -6]).sort_values()

4   -6.0
3   -2.0
1    2.0
2    3.0
0    NaN
dtype: float64